# -------------------------------------------------------------------
# COMANDO D (Definir Tipo de VM)
# Sintaxe:
# D <TIPO_VM> <DIR_INPUTS> <CAMINHO_EXEC> <RAM> <DISCO> <VCPUS>
# -------------------------------------------------------------------
# Exemplo 1: Define a VM "V1" (2GB RAM, 50GB Disco, 4 vCPUs)
D V1 /tmp/v1-inputs /usr/bin/v1_app 2 50 4
